-- MySQL Script generated by MySQL Workbench
-- Fri Sep 18 23:49:26 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `test` ;

-- -----------------------------------------------------
-- Table `test`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`employees` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(255) NOT NULL,
  `position` VARCHAR(255) NULL DEFAULT NULL,
  `department` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `employee_number` VARCHAR(50) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `telegram_id` VARCHAR(50) NULL DEFAULT NULL,
  `role` ENUM('admin', 'viewer') NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  UNIQUE INDEX `employee_number` (`employee_number` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `test`.`certificates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`certificates` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `employee_id` INT NOT NULL,
  `serial_number` VARCHAR(100) NOT NULL,
  `issuer` VARCHAR(500) NOT NULL,
  `subject` VARCHAR(500) NOT NULL,
  `valid_from` DATETIME NOT NULL,
  `valid_to` DATETIME NOT NULL,
  `thumbprint_sha1` VARCHAR(64) NULL DEFAULT NULL,
  `thumbprint_sha256` VARCHAR(128) NULL DEFAULT NULL,
  `public_key` TEXT NULL DEFAULT NULL,
  `key_usage` TEXT NULL DEFAULT NULL,
  `notes` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unique_cert` (`serial_number` ASC, `issuer` ASC) VISIBLE,
  INDEX `employee_id` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `certificates_ibfk_1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `test`.`employees` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 35
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `test`.`registration_keys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`registration_keys` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `emp_id` INT NOT NULL,
  `uniqkey` VARCHAR(64) NOT NULL,
  `is_used` TINYINT(1) NULL DEFAULT '0',
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `used_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uniqkey` (`uniqkey` ASC) VISIBLE,
  INDEX `idx_uniqkey` (`uniqkey` ASC) VISIBLE,
  INDEX `idx_emp_id` (`emp_id` ASC) VISIBLE,
  CONSTRAINT `registration_keys_ibfk_1`
    FOREIGN KEY (`emp_id`)
    REFERENCES `test`.`employees` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `test`.`userreg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`userreg` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Уникальный ID пользователя системы',
  `emp_id` INT NOT NULL COMMENT 'Ссылка на сотрудника (employees.id)',
  `username` VARCHAR(80) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL COMMENT 'Логин для входа (например, login@company)',
  `email` VARCHAR(120) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL COMMENT 'Email (должен быть уникальным)',
  `password_hash` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL COMMENT 'Хеш пароля (pbkdf2:sha256 или bcrypt)',
  `role` ENUM('admin', 'operator', 'viewer') CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT 'viewer' COMMENT 'Роль в системе управления',
  `is_active` TINYINT(1) NULL DEFAULT '1' COMMENT 'Активен ли аккаунт (для блокировки без удаления)',
  `telegram_id` BIGINT NULL DEFAULT NULL COMMENT 'Telegram ID для привязки бота (если используется)',
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Дата регистрации',
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Дата последнего обновления',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  UNIQUE INDEX `telegram_id` (`telegram_id` ASC) VISIBLE,
  INDEX `fk_userreg_employee` (`emp_id` ASC) VISIBLE,
  CONSTRAINT `fk_userreg_employee`
    FOREIGN KEY (`emp_id`)
    REFERENCES `test`.`employees` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
